from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import Response
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.core.database import get_db
from app.core.config import settings
from app.models.models import Report, Competitor, User
from jose import jwt
from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
import logging

logger = logging.getLogger(__name__)
router = APIRouter()

async def get_user_from_token(token: str, db: AsyncSession):
    try:
        payload = jwt.decode(token, settings.JWT_SECRET, algorithms=[settings.JWT_ALGORITHM])
        user_id = int(payload.get("sub"))
        return user_id
    except Exception:
        raise HTTPException(status_code=401, detail="Invalid token")

@router.get("/brief/{report_id}")
async def export_brief_pdf(report_id: int, token: str = Query(...), db: AsyncSession = Depends(get_db)):
    user_id = await get_user_from_token(token, db)
    
    result = await db.execute(select(Report).where(Report.id == report_id))
    report = result.scalar_one_or_none()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
    
    comp_result = await db.execute(select(Competitor).where(Competitor.id == report.competitor_id))
    comp = comp_result.scalar_one_or_none()
    comp_name = comp.name if comp else "Unknown"
    
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=25*mm, rightMargin=25*mm, topMargin=25*mm, bottomMargin=25*mm)
    styles = getSampleStyleSheet()
    ts = ParagraphStyle('T', parent=styles['Title'], fontSize=20, textColor=HexColor('#6366f1'), spaceAfter=6)
    ss = ParagraphStyle('S', parent=styles['Normal'], fontSize=10, textColor=HexColor('#64748b'), spaceAfter=20)
    hs = ParagraphStyle('H', parent=styles['Heading2'], fontSize=13, textColor=HexColor('#6366f1'), spaceBefore=16, spaceAfter=8)
    bs = ParagraphStyle('B', parent=styles['Normal'], fontSize=11, textColor=HexColor('#1e293b'), leading=16, spaceAfter=10)
    
    elements = []
    elements.append(Paragraph("CompetitorRadar AI", ts))
    elements.append(Paragraph("Strategic Intelligence Brief - " + comp_name, ss))
    elements.append(Spacer(1, 10))
    if report.title:
        elements.append(Paragraph(report.title, ParagraphStyle('BT', parent=styles['Heading1'], fontSize=16, textColor=HexColor('#0f172a'))))
        elements.append(Spacer(1, 10))
    for title, content in [("WHAT CHANGED", report.what_changed), ("WHY IT MATTERS", report.why_it_matters), ("WHAT YOU SHOULD DO", report.what_to_do), ("THREAT LEVEL", report.threat_level)]:
        if content:
            elements.append(Paragraph(title, hs))
            for line in content.split('\n'):
                if line.strip():
                    elements.append(Paragraph(line.strip(), bs))
    elements.append(Spacer(1, 30))
    elements.append(Paragraph("Generated by CompetitorRadar AI - comp-radar.com", ParagraphStyle('F', parent=styles['Normal'], fontSize=8, textColor=HexColor('#94a3b8'))))
    doc.build(elements)
    buf.seek(0)
    filename = "CompetitorRadar_" + comp_name.replace(' ','_') + "_Brief.pdf"
    return Response(content=buf.read(), media_type="application/pdf", headers={"Content-Disposition": "attachment; filename=" + filename})

@router.get("/all")
async def export_all_briefs(token: str = Query(...), db: AsyncSession = Depends(get_db)):
    user_id = await get_user_from_token(token, db)
    
    result = await db.execute(select(Report, Competitor.name).join(Competitor).where(Competitor.user_id == user_id).order_by(Report.created_at.desc()))
    rows = result.all()
    if not rows:
        raise HTTPException(status_code=404, detail="No reports found")
    
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=25*mm, rightMargin=25*mm, topMargin=25*mm, bottomMargin=25*mm)
    styles = getSampleStyleSheet()
    ts = ParagraphStyle('T', parent=styles['Title'], fontSize=20, textColor=HexColor('#6366f1'), spaceAfter=6)
    ss = ParagraphStyle('S', parent=styles['Normal'], fontSize=10, textColor=HexColor('#64748b'), spaceAfter=20)
    hs = ParagraphStyle('H', parent=styles['Heading2'], fontSize=13, textColor=HexColor('#6366f1'), spaceBefore=16, spaceAfter=8)
    bs = ParagraphStyle('B', parent=styles['Normal'], fontSize=11, textColor=HexColor('#1e293b'), leading=16, spaceAfter=10)
    cs = ParagraphStyle('C', parent=styles['Heading1'], fontSize=16, textColor=HexColor('#0f172a'), spaceBefore=30)
    
    elements = []
    elements.append(Paragraph("CompetitorRadar AI", ts))
    elements.append(Paragraph("All Intelligence Briefs - " + str(len(rows)) + " reports", ss))
    for report, comp_name in rows:
        elements.append(Paragraph(comp_name + " - " + (report.title or 'Brief'), cs))
        for title, content in [("WHAT CHANGED", report.what_changed), ("WHY IT MATTERS", report.why_it_matters), ("WHAT TO DO", report.what_to_do), ("THREAT LEVEL", report.threat_level)]:
            if content:
                elements.append(Paragraph(title, hs))
                for line in content.split('\n'):
                    if line.strip():
                        elements.append(Paragraph(line.strip(), bs))
    elements.append(Spacer(1, 30))
    elements.append(Paragraph("Generated by CompetitorRadar AI - comp-radar.com", ParagraphStyle('F', parent=styles['Normal'], fontSize=8, textColor=HexColor('#94a3b8'))))
    doc.build(elements)
    buf.seek(0)
    return Response(content=buf.read(), media_type="application/pdf", headers={"Content-Disposition": "attachment; filename=CompetitorRadar_All_Briefs.pdf"})
