from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.core.database import get_db
from app.core.auth import get_current_user
from app.models.models import Report, Competitor
from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
import logging

logger = logging.getLogger(__name__)
router = APIRouter()

@router.get("/brief/{report_id}")
async def export_brief_pdf(report_id: int, current_user: dict = Depends(get_current_user), db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(Report).where(Report.id == report_id))
    report = result.scalar_one_or_none()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
    
    comp_result = await db.execute(select(Competitor).where(Competitor.id == report.competitor_id))
    comp = comp_result.scalar_one_or_none()
    comp_name = comp.name if comp else "Unknown"
    
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=25*mm, rightMargin=25*mm, topMargin=25*mm, bottomMargin=25*mm)
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle('Title2', parent=styles['Title'], fontSize=20, textColor=HexColor('#6366f1'), spaceAfter=6)
    sub_style = ParagraphStyle('Sub', parent=styles['Normal'], fontSize=10, textColor=HexColor('#64748b'), spaceAfter=20)
    heading_style = ParagraphStyle('H2', parent=styles['Heading2'], fontSize=13, textColor=HexColor('#6366f1'), spaceBefore=16, spaceAfter=8)
    body_style = ParagraphStyle('Body2', parent=styles['Normal'], fontSize=11, textColor=HexColor('#1e293b'), leading=16, spaceAfter=10)
    threat_style = ParagraphStyle('Threat', parent=styles['Normal'], fontSize=12, textColor=HexColor('#ef4444'), spaceBefore=10)
    
    elements = []
    elements.append(Paragraph("CompetitorRadar AI", title_style))
    elements.append(Paragraph(f"Strategic Intelligence Brief — {comp_name}", sub_style))
    elements.append(Spacer(1, 10))
    
    if report.title:
        elements.append(Paragraph(report.title, ParagraphStyle('BriefTitle', parent=styles['Heading1'], fontSize=16, textColor=HexColor('#0f172a'))))
        elements.append(Spacer(1, 10))
    
    sections = [
        ("WHAT CHANGED", report.what_changed),
        ("WHY IT MATTERS", report.why_it_matters),
        ("WHAT YOU SHOULD DO", report.what_to_do),
        ("THREAT LEVEL", report.threat_level),
    ]
    
    for title, content in sections:
        if content:
            elements.append(Paragraph(title, heading_style))
            for line in content.split('\n'):
                if line.strip():
                    elements.append(Paragraph(line.strip(), body_style))
    
    elements.append(Spacer(1, 30))
    elements.append(Paragraph(f"Generated by CompetitorRadar AI — comp-radar.com", ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=HexColor('#94a3b8'))))
    
    doc.build(elements)
    buf.seek(0)
    
    filename = f"CompetitorRadar_{comp_name.replace(' ','_')}_Brief.pdf"
    return Response(content=buf.read(), media_type="application/pdf", headers={"Content-Disposition": f"attachment; filename={filename}"})


@router.get("/all")
async def export_all_briefs(current_user: dict = Depends(get_current_user), db: AsyncSession = Depends(get_db)):
    result = await db.execute(
        select(Report, Competitor.name)
        .join(Competitor)
        .join(Competitor.user)
        .where(Competitor.user_id == current_user["user_id"])
        .order_by(Report.created_at.desc())
    )
    rows = result.all()
    if not rows:
        raise HTTPException(status_code=404, detail="No reports found")
    
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=25*mm, rightMargin=25*mm, topMargin=25*mm, bottomMargin=25*mm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('T', parent=styles['Title'], fontSize=20, textColor=HexColor('#6366f1'), spaceAfter=6)
    sub_style = ParagraphStyle('S', parent=styles['Normal'], fontSize=10, textColor=HexColor('#64748b'), spaceAfter=20)
    heading_style = ParagraphStyle('H', parent=styles['Heading2'], fontSize=13, textColor=HexColor('#6366f1'), spaceBefore=16, spaceAfter=8)
    body_style = ParagraphStyle('B', parent=styles['Normal'], fontSize=11, textColor=HexColor('#1e293b'), leading=16, spaceAfter=10)
    comp_style = ParagraphStyle('C', parent=styles['Heading1'], fontSize=16, textColor=HexColor('#0f172a'), spaceBefore=30)
    
    elements = []
    elements.append(Paragraph("CompetitorRadar AI", title_style))
    elements.append(Paragraph(f"All Intelligence Briefs — {len(rows)} reports", sub_style))
    
    for report, comp_name in rows:
        elements.append(Paragraph(f"{comp_name} — {report.title or 'Brief'}", comp_style))
        for title, content in [("WHAT CHANGED", report.what_changed), ("WHY IT MATTERS", report.why_it_matters), ("WHAT TO DO", report.what_to_do), ("THREAT LEVEL", report.threat_level)]:
            if content:
                elements.append(Paragraph(title, heading_style))
                for line in content.split('\n'):
                    if line.strip():
                        elements.append(Paragraph(line.strip(), body_style))
    
    elements.append(Spacer(1, 30))
    elements.append(Paragraph("Generated by CompetitorRadar AI — comp-radar.com", ParagraphStyle('F', parent=styles['Normal'], fontSize=8, textColor=HexColor('#94a3b8'))))
    
    doc.build(elements)
    buf.seek(0)
    return Response(content=buf.read(), media_type="application/pdf", headers={"Content-Disposition": "attachment; filename=CompetitorRadar_All_Briefs.pdf"})